name: Test zk and algebra

on: [push, pull_request]

jobs:
  build_wheels:
    name: Build ${{ matrix.target }} on ${{ matrix.os }}
    env:
      boost_version: "1.76.0"
      python_version: "3.9"
      zk_targets: "zk_r1cs_gg_ppzksnark_test"
      algebra_targets: "algebra_fields_test algebra_curves_test algebra_pairing_test"
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest]
        target: [zk, algebra]

    steps:
      - name: Cancel previous runs on the same branch
        if: ${{ github.ref != 'refs/heads/main' }}
        uses: styfle/cancel-workflow-action@0.7.0
        with:
          access_token: ${{ github.token }}

      - name: Set additional env value
        id: set_env_value
        run: |
          echo "workspace=$GITHUB_WORKSPACE" >> $GITHUB_ENV
          cd $GITHUB_WORKSPACE/../
          echo "root_workspace=$(pwd)" >> $GITHUB_ENV
          echo "boost_version_load=$(echo ${{ env.boost_version }} | sed "s/\./\_/g")"  >> $GITHUB_ENV

      - name: Set nproc
        if: startsWith(matrix.os, 'macos')
        run: |
          echo "nproc=$(sysctl -n hw.ncpu)" >> $GITHUB_ENV

      - name: Set nproc
        if: startsWith(matrix.os, 'ubuntu')
        run: |
          echo "nproc=`nproc`" >> $GITHUB_ENV

      - name: Set targets
        run: |
          if [[ ${{ matrix.target }} == zk ]]; then
             echo "targets=${{ env.zk_targets }}" >> $GITHUB_ENV
          fi
          if [[ ${{ matrix.target }} == algebra ]]; then
             echo "targets=${{ env.algebra_targets }}" >> $GITHUB_ENV
          fi

      - name: Checkout code
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - uses: actions/setup-python@v2
        name: Install Python
        id: python-installer
        with:
          python-version: ${{ env.python_version }}

      - name: Cache boost
        id: cache-boost
        uses: actions/cache@v2
        with:
          path: |
            ${{ env.root_workspace }}/boost
          key: boost-${{ runner.os }}-${{ env.root_workspace }}-${{ env.python_version }}

      - name: Install boost
        if: steps.cache-boost.outputs.cache-hit != 'true'
        run: |
          wget -nv -O boost.tar.gz https://boostorg.jfrog.io/artifactory/main/release/${{ env.boost_version }}/source/boost_${{ env.boost_version_load }}.tar.gz &&
          tar xzf boost.tar.gz -C ~/ &&
          cd ~/boost_${{ env.boost_version_load }}/ &&
          ./bootstrap.sh --with-python=/opt/hostedtoolcache/Python/3.9.6/x64/bin/python${{ env.python_version }} --with-python-version=${{ env.python_version }} --prefix=${{ env.root_workspace }}/boost &&
          ./b2 -j ${{ env.nproc }} &&  sudo ./b2 install -j ${{ env.nproc }}

      - name: Cmake and build
        run: |
          mkdir build
          cd build
          cmake .. -DBOOST_ROOT=${{ env.root_workspace }}/boost
          cmake --build . -t ${{ env.targets }} -- -j ${{ env.nproc }}

      - name: Ctest
        continue-on-error: true
        run: |
          ctest
